name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r dex-backend-upload/requirements.txt

    - - name: Syntax check
        run: |
                python -m compileall dex-backend-upload/src
               

      - name: Placeholder tests
        run: |
          echo "Running backend tests..."
          # Add your test commands here once tests exist
