name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r dex-backend-upload/requirements.txt

      - name: Lint Python code
        run: |
          pip install flake8 black
          flake8 dex-backend-upload
          black --check dex-backend-upload

      - name: Placeholder tests
        run: |
          echo "Running backend tests..."
          # Add your test commands here once tests exist
