name: rust-clippy analyze

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Skip rust-clippy
        run: echo "No Rust code to analyze in this backend repository"
